#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Start Container
# -------------------------------------------------------------------------------------------
PORT=9090
ORG=`../getServiceName 1`
SERVICE=`../getServiceName 4`
API=`../getServiceName 3`
CN=`../getServiceName 2`
echo "docker container run --name $CN -d --rm -p $PORT:8080 $ORG/$SERVICE"
docker container run --name $CN -d --rm -p $PORT:8080 $ORG/$SERVICE
echo "Container id for $CN ="`docker container ls | grep $CN | tr -s " " | cut -d " " -f 1`
docker container ls | grep $CN | tr -s " " | cut -d " " -f 1 > $CN.cid
